config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :users, only: [:show] do
    resources :apps do
      resources :events
    end
  end
  
  namespace :api, defaults: {format: :json} do
    resources :events, only: [:create]
  end
  
  get 'welcome/index'

  
  root to: "welcome#index"
end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :app
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apps
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
    
  def create
    app = App.find_by(url: request.env['HTTP_ORIGIN'])
    @event = app.events.build(event_params)
    
    if app.nil?
      render json: "Invalid Application", status: :unprocessable_entity
    elsif @event.save
      render json: @event, status: :created
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end
  
  private
  
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def new
    @app = App.new
  end
  
  def create
    @app = current_user.apps.build(app_params)
    
    if @app.save
      flash[:notice] = "App saved successfully"
      redirect_to [current_user, @app]
    else
      flash[:error] = "App failed to save. Please try again later"
      render :edit
    end
  
  end
  
  def show
    @app = App.find(params[:id])
    @events = @app.events
  end
  
  def index
    @apps = current_user.apps
  end
  
  def edit
    @app = App.find(params[:id])
  end
  
  def update
    @app = App.find(params[:id])
    if @app.update_attributes(app_params)
      redirect_to [current_user, @app], notice: "App updated"
    else
      flash[:error] = "App failed to update. Please try again later"
      render :edit
    end
  end
  
  def destroy
    @app = App.find(params[:id])
    
    if @app.destroy
      redirect_to user_apps_path, notice: "App deleted successfully"
    else
      flash[:error] = "App failed to delete. Please try again"
      render :show
    end
  end
  
  private
  
  def app_params
    params.require(:app).permit(:name, :url)
  end
end
# curl -v -H "Accept: application/json" -H "Origin: https://www.facebook.com" -H "Content-Type: application/json" -X POST -d '{"event":{"name":"foobar"}}' https://metrics-api-devtheory.c9.io/api/events

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/apps/edit.html.erb
<h1>Edit App</h1>
<%= form_for [current_user, @app] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/apps/index.html.erb
<h1><%= "#{current_user.email}'s Apps" %></h1>

<ul>
  <% @apps.each do |app| %>
    <li><%= link_to app.name, [current_user, app] %></li>
  <% end %>
</ul>

app/views/apps/new.html.erb
<h1>New App</h1>
<%= form_for [current_user, @app] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/apps/show.html.erb
<h1><%= @app.name %></h1>
<h4>Number of events: <%= @events ? @events.count : "0" %></h4>
<%= @app.url %>
<%= link_to "Edit", edit_user_app_path(current_user, @app) %>
<%= link_to "Remove", [current_user, @app], method: :delete %>

<h2>Events</h2>
<ul>
    <% @events.each do |event| %>
        <li><%= event.name %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>